-- CREATE ROLES

CREATE ROLE db_admin NOLOGIN;
CREATE ROLE db_manager NOLOGIN;
CREATE ROLE data_uploader NOLOGIN;
CREATE ROLE data_analyst NOLOGIN;

-- LETS ROLES SEE THAT THE PUBLIC SCHEMA EXISTS

GRANT USAGE ON SCHEMA public TO db_admin;
GRANT USAGE ON SCHEMA public TO db_manager;
GRANT USAGE ON SCHEMA public TO data_uploader;
GRANT USAGE ON SCHEMA public TO data_analyst;

-- ADMIN

GRANT ALL PRIVILEGES 
ON ALL TABLES IN SCHEMA public
TO db_admin;

GRANT ALL PRIVILEGES 
ON ALL SEQUENCES IN SCHEMA public
TO db_admin;

-- MANAGER

GRANT
SELECT,
INSERT,
UPDATE,
DELETE,
TRUNCATE,
REFERENCES,
TRIGGER
ON ALL TABLES IN SCHEMA public
TO db_manager;

-- DATA UPLOADER

GRANT
SELECT,
INSERT
ON ALL TABLES IN SCHEMA public
TO data_uploader;

-- DATA ANALYST

GRANT
SELECT
ON ALL TABLES IN SCHEMA public
TO data_analyst;

-- DEFAULT PRIVILEGES FOR FUTURE TABLES

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO db_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT
SELECT,
INSERT,
UPDATE,
DELETE,
TRUNCATE,
REFERENCES,
TRIGGER
ON TABLES TO db_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT
SELECT,
INSERT
ON TABLES TO data_uploader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT
SELECT
ON TABLES TO data_analyst;

-- DEFAULT PRIVILEGES FOR FUTURE SEQUENCES

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO db_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO db_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO data_uploader;

-- CURRENT SEQUENCE ACCESS FOR DATA UPLOADER
GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO data_uploader;

-- CURRENT SCHEMA CREATE ACCESS FOR ADMIN
GRANT CREATE ON SCHEMA public TO db_admin;

-- MANAGER SEQUENCE ACCESS FOR CURRENT SEQUENCES

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO db_manager;

-- ADMIN CAN CREATE OBJECTS IN PUBLIC SCHEMA

GRANT CREATE ON SCHEMA public TO db_admin;